configuration_profile:
  explorer:
    dark_mode: true
    search_box: hidden
    file_extensions: shown
    hidden_files: shown
    start_menu_alignment: left
  date time settings:
    show seconds in taskbar: on
    custom short date pattern: on
    custom long date pattern: on
    custom time pattern: on
    24 hour time format: on
    set first day of the week to Monday: on
  powershell modules: |
    C:\powershell-modules\
  ssh: on