# 
# Module manifest for module 'MyModule'
#
# Generated by: Peter Burbery
# Generated on: 6/24/2025
@
{
RootModule = 'MyModule.psm1'
ModuleVersion = '1.0.0'
GUID = 'b7506fca-a75b-46be-9cf0-90b16571bedb'
Author = 'Peter Cullen Burbery'
CompanyName = 'Unknown'
Copyright = '(c) Peter Burbery. Some rights reserved.'
Description = 'PowerShell utilities for configuring Windows systems, managing environments, customizing time and date settings, and automating administrative tasks.'
FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
PrivateData = @{
    PSData = @{
    }
}
}
